// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-web/lesson/chapter5_1/repository/ent/goodscategory"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// GoodsCategory is the model entity for the GoodsCategory schema.
type GoodsCategory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoodsCategoryQuery when eager-loading is set.
	Edges GoodsCategoryEdges `json:"edges"`
}

// GoodsCategoryEdges holds the relations/edges for other nodes in the graph.
type GoodsCategoryEdges struct {
	// Goods holds the value of the goods edge.
	Goods []*Goods `json:"goods,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GoodsOrErr returns the Goods value or an error if the edge
// was not loaded in eager-loading.
func (e GoodsCategoryEdges) GoodsOrErr() ([]*Goods, error) {
	if e.loadedTypes[0] {
		return e.Goods, nil
	}
	return nil, &NotLoadedError{edge: "goods"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoodsCategory) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case goodscategory.FieldID:
			values[i] = new(sql.NullInt64)
		case goodscategory.FieldName:
			values[i] = new(sql.NullString)
		case goodscategory.FieldCreateTime, goodscategory.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type GoodsCategory", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoodsCategory fields.
func (gc *GoodsCategory) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goodscategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gc.ID = int(value.Int64)
		case goodscategory.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				gc.CreateTime = value.Time
			}
		case goodscategory.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				gc.UpdateTime = value.Time
			}
		case goodscategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gc.Name = value.String
			}
		}
	}
	return nil
}

// QueryGoods queries the "goods" edge of the GoodsCategory entity.
func (gc *GoodsCategory) QueryGoods() *GoodsQuery {
	return (&GoodsCategoryClient{config: gc.config}).QueryGoods(gc)
}

// Update returns a builder for updating this GoodsCategory.
// Note that you need to call GoodsCategory.Unwrap() before calling this method if this GoodsCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (gc *GoodsCategory) Update() *GoodsCategoryUpdateOne {
	return (&GoodsCategoryClient{config: gc.config}).UpdateOne(gc)
}

// Unwrap unwraps the GoodsCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gc *GoodsCategory) Unwrap() *GoodsCategory {
	tx, ok := gc.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoodsCategory is not a transactional entity")
	}
	gc.config.driver = tx.drv
	return gc
}

// String implements the fmt.Stringer.
func (gc *GoodsCategory) String() string {
	var builder strings.Builder
	builder.WriteString("GoodsCategory(")
	builder.WriteString(fmt.Sprintf("id=%v", gc.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(gc.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(gc.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", name=")
	builder.WriteString(gc.Name)
	builder.WriteByte(')')
	return builder.String()
}

// GoodsCategories is a parsable slice of GoodsCategory.
type GoodsCategories []*GoodsCategory

func (gc GoodsCategories) config(cfg config) {
	for _i := range gc {
		gc[_i].config = cfg
	}
}
