// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// ItemCategory is the predicate function for itemcategory builders.
type ItemCategory func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
