// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Goods is the predicate function for goods builders.
type Goods func(*sql.Selector)

// GoodsCategory is the predicate function for goodscategory builders.
type GoodsCategory func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
