// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"go-web/lesson/chapter6_1/repository/ent/goods"
	"go-web/lesson/chapter6_1/repository/ent/goodscategory"
	"go-web/lesson/chapter6_1/repository/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoodsCategoryQuery is the builder for querying GoodsCategory entities.
type GoodsCategoryQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GoodsCategory
	// eager-loading edges.
	withGoods *GoodsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoodsCategoryQuery builder.
func (gcq *GoodsCategoryQuery) Where(ps ...predicate.GoodsCategory) *GoodsCategoryQuery {
	gcq.predicates = append(gcq.predicates, ps...)
	return gcq
}

// Limit adds a limit step to the query.
func (gcq *GoodsCategoryQuery) Limit(limit int) *GoodsCategoryQuery {
	gcq.limit = &limit
	return gcq
}

// Offset adds an offset step to the query.
func (gcq *GoodsCategoryQuery) Offset(offset int) *GoodsCategoryQuery {
	gcq.offset = &offset
	return gcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gcq *GoodsCategoryQuery) Unique(unique bool) *GoodsCategoryQuery {
	gcq.unique = &unique
	return gcq
}

// Order adds an order step to the query.
func (gcq *GoodsCategoryQuery) Order(o ...OrderFunc) *GoodsCategoryQuery {
	gcq.order = append(gcq.order, o...)
	return gcq
}

// QueryGoods chains the current query on the "goods" edge.
func (gcq *GoodsCategoryQuery) QueryGoods() *GoodsQuery {
	query := &GoodsQuery{config: gcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goodscategory.Table, goodscategory.FieldID, selector),
			sqlgraph.To(goods.Table, goods.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goodscategory.GoodsTable, goodscategory.GoodsColumn),
		)
		fromU = sqlgraph.SetNeighbors(gcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoodsCategory entity from the query.
// Returns a *NotFoundError when no GoodsCategory was found.
func (gcq *GoodsCategoryQuery) First(ctx context.Context) (*GoodsCategory, error) {
	nodes, err := gcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goodscategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) FirstX(ctx context.Context) *GoodsCategory {
	node, err := gcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoodsCategory ID from the query.
// Returns a *NotFoundError when no GoodsCategory ID was found.
func (gcq *GoodsCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goodscategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := gcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoodsCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one GoodsCategory entity is not found.
// Returns a *NotFoundError when no GoodsCategory entities are found.
func (gcq *GoodsCategoryQuery) Only(ctx context.Context) (*GoodsCategory, error) {
	nodes, err := gcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goodscategory.Label}
	default:
		return nil, &NotSingularError{goodscategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) OnlyX(ctx context.Context) *GoodsCategory {
	node, err := gcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoodsCategory ID in the query.
// Returns a *NotSingularError when exactly one GoodsCategory ID is not found.
// Returns a *NotFoundError when no entities are found.
func (gcq *GoodsCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = &NotSingularError{goodscategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := gcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoodsCategories.
func (gcq *GoodsCategoryQuery) All(ctx context.Context) ([]*GoodsCategory, error) {
	if err := gcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) AllX(ctx context.Context) []*GoodsCategory {
	nodes, err := gcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoodsCategory IDs.
func (gcq *GoodsCategoryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gcq.Select(goodscategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := gcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gcq *GoodsCategoryQuery) Count(ctx context.Context) (int, error) {
	if err := gcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) CountX(ctx context.Context) int {
	count, err := gcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gcq *GoodsCategoryQuery) Exist(ctx context.Context) (bool, error) {
	if err := gcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gcq *GoodsCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := gcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoodsCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gcq *GoodsCategoryQuery) Clone() *GoodsCategoryQuery {
	if gcq == nil {
		return nil
	}
	return &GoodsCategoryQuery{
		config:     gcq.config,
		limit:      gcq.limit,
		offset:     gcq.offset,
		order:      append([]OrderFunc{}, gcq.order...),
		predicates: append([]predicate.GoodsCategory{}, gcq.predicates...),
		withGoods:  gcq.withGoods.Clone(),
		// clone intermediate query.
		sql:  gcq.sql.Clone(),
		path: gcq.path,
	}
}

// WithGoods tells the query-builder to eager-load the nodes that are connected to
// the "goods" edge. The optional arguments are used to configure the query builder of the edge.
func (gcq *GoodsCategoryQuery) WithGoods(opts ...func(*GoodsQuery)) *GoodsCategoryQuery {
	query := &GoodsQuery{config: gcq.config}
	for _, opt := range opts {
		opt(query)
	}
	gcq.withGoods = query
	return gcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoodsCategory.Query().
//		GroupBy(goodscategory.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (gcq *GoodsCategoryQuery) GroupBy(field string, fields ...string) *GoodsCategoryGroupBy {
	group := &GoodsCategoryGroupBy{config: gcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.GoodsCategory.Query().
//		Select(goodscategory.FieldCreateTime).
//		Scan(ctx, &v)
//
func (gcq *GoodsCategoryQuery) Select(fields ...string) *GoodsCategorySelect {
	gcq.fields = append(gcq.fields, fields...)
	return &GoodsCategorySelect{GoodsCategoryQuery: gcq}
}

func (gcq *GoodsCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gcq.fields {
		if !goodscategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gcq.path != nil {
		prev, err := gcq.path(ctx)
		if err != nil {
			return err
		}
		gcq.sql = prev
	}
	return nil
}

func (gcq *GoodsCategoryQuery) sqlAll(ctx context.Context) ([]*GoodsCategory, error) {
	var (
		nodes       = []*GoodsCategory{}
		_spec       = gcq.querySpec()
		loadedTypes = [1]bool{
			gcq.withGoods != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &GoodsCategory{config: gcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, gcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := gcq.withGoods; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*GoodsCategory)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Goods = []*Goods{}
		}
		query.Where(predicate.Goods(func(s *sql.Selector) {
			s.Where(sql.InValues(goodscategory.GoodsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.CategoryID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "category_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Goods = append(node.Edges.Goods, n)
		}
	}

	return nodes, nil
}

func (gcq *GoodsCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gcq.querySpec()
	return sqlgraph.CountNodes(ctx, gcq.driver, _spec)
}

func (gcq *GoodsCategoryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gcq *GoodsCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   goodscategory.Table,
			Columns: goodscategory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: goodscategory.FieldID,
			},
		},
		From:   gcq.sql,
		Unique: true,
	}
	if unique := gcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goodscategory.FieldID)
		for i := range fields {
			if fields[i] != goodscategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gcq *GoodsCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gcq.driver.Dialect())
	t1 := builder.Table(goodscategory.Table)
	columns := gcq.fields
	if len(columns) == 0 {
		columns = goodscategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gcq.sql != nil {
		selector = gcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range gcq.predicates {
		p(selector)
	}
	for _, p := range gcq.order {
		p(selector)
	}
	if offset := gcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoodsCategoryGroupBy is the group-by builder for GoodsCategory entities.
type GoodsCategoryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gcgb *GoodsCategoryGroupBy) Aggregate(fns ...AggregateFunc) *GoodsCategoryGroupBy {
	gcgb.fns = append(gcgb.fns, fns...)
	return gcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gcgb *GoodsCategoryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := gcgb.path(ctx)
	if err != nil {
		return err
	}
	gcgb.sql = query
	return gcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := gcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(gcgb.fields) > 1 {
		return nil, errors.New("ent: GoodsCategoryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := gcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) StringsX(ctx context.Context) []string {
	v, err := gcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategoryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) StringX(ctx context.Context) string {
	v, err := gcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(gcgb.fields) > 1 {
		return nil, errors.New("ent: GoodsCategoryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := gcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) IntsX(ctx context.Context) []int {
	v, err := gcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategoryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) IntX(ctx context.Context) int {
	v, err := gcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(gcgb.fields) > 1 {
		return nil, errors.New("ent: GoodsCategoryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := gcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := gcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategoryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := gcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(gcgb.fields) > 1 {
		return nil, errors.New("ent: GoodsCategoryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := gcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := gcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (gcgb *GoodsCategoryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategoryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gcgb *GoodsCategoryGroupBy) BoolX(ctx context.Context) bool {
	v, err := gcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gcgb *GoodsCategoryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range gcgb.fields {
		if !goodscategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gcgb *GoodsCategoryGroupBy) sqlQuery() *sql.Selector {
	selector := gcgb.sql.Select()
	aggregation := make([]string, 0, len(gcgb.fns))
	for _, fn := range gcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gcgb.fields)+len(gcgb.fns))
		for _, f := range gcgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gcgb.fields...)...)
}

// GoodsCategorySelect is the builder for selecting fields of GoodsCategory entities.
type GoodsCategorySelect struct {
	*GoodsCategoryQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gcs *GoodsCategorySelect) Scan(ctx context.Context, v interface{}) error {
	if err := gcs.prepareQuery(ctx); err != nil {
		return err
	}
	gcs.sql = gcs.GoodsCategoryQuery.sqlQuery(ctx)
	return gcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (gcs *GoodsCategorySelect) ScanX(ctx context.Context, v interface{}) {
	if err := gcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Strings(ctx context.Context) ([]string, error) {
	if len(gcs.fields) > 1 {
		return nil, errors.New("ent: GoodsCategorySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := gcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (gcs *GoodsCategorySelect) StringsX(ctx context.Context) []string {
	v, err := gcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = gcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategorySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (gcs *GoodsCategorySelect) StringX(ctx context.Context) string {
	v, err := gcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Ints(ctx context.Context) ([]int, error) {
	if len(gcs.fields) > 1 {
		return nil, errors.New("ent: GoodsCategorySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := gcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (gcs *GoodsCategorySelect) IntsX(ctx context.Context) []int {
	v, err := gcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = gcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategorySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (gcs *GoodsCategorySelect) IntX(ctx context.Context) int {
	v, err := gcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(gcs.fields) > 1 {
		return nil, errors.New("ent: GoodsCategorySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := gcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (gcs *GoodsCategorySelect) Float64sX(ctx context.Context) []float64 {
	v, err := gcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = gcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategorySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (gcs *GoodsCategorySelect) Float64X(ctx context.Context) float64 {
	v, err := gcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(gcs.fields) > 1 {
		return nil, errors.New("ent: GoodsCategorySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := gcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (gcs *GoodsCategorySelect) BoolsX(ctx context.Context) []bool {
	v, err := gcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (gcs *GoodsCategorySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = gcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{goodscategory.Label}
	default:
		err = fmt.Errorf("ent: GoodsCategorySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (gcs *GoodsCategorySelect) BoolX(ctx context.Context) bool {
	v, err := gcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (gcs *GoodsCategorySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := gcs.sql.Query()
	if err := gcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
