// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-web/lesson/chapter6_1/repository/ent/goods"
	"go-web/lesson/chapter6_1/repository/ent/goodscategory"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoodsCategoryCreate is the builder for creating a GoodsCategory entity.
type GoodsCategoryCreate struct {
	config
	mutation *GoodsCategoryMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (gcc *GoodsCategoryCreate) SetCreateTime(t time.Time) *GoodsCategoryCreate {
	gcc.mutation.SetCreateTime(t)
	return gcc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (gcc *GoodsCategoryCreate) SetNillableCreateTime(t *time.Time) *GoodsCategoryCreate {
	if t != nil {
		gcc.SetCreateTime(*t)
	}
	return gcc
}

// SetUpdateTime sets the "update_time" field.
func (gcc *GoodsCategoryCreate) SetUpdateTime(t time.Time) *GoodsCategoryCreate {
	gcc.mutation.SetUpdateTime(t)
	return gcc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (gcc *GoodsCategoryCreate) SetNillableUpdateTime(t *time.Time) *GoodsCategoryCreate {
	if t != nil {
		gcc.SetUpdateTime(*t)
	}
	return gcc
}

// SetName sets the "name" field.
func (gcc *GoodsCategoryCreate) SetName(s string) *GoodsCategoryCreate {
	gcc.mutation.SetName(s)
	return gcc
}

// AddGoodIDs adds the "goods" edge to the Goods entity by IDs.
func (gcc *GoodsCategoryCreate) AddGoodIDs(ids ...int) *GoodsCategoryCreate {
	gcc.mutation.AddGoodIDs(ids...)
	return gcc
}

// AddGoods adds the "goods" edges to the Goods entity.
func (gcc *GoodsCategoryCreate) AddGoods(g ...*Goods) *GoodsCategoryCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return gcc.AddGoodIDs(ids...)
}

// Mutation returns the GoodsCategoryMutation object of the builder.
func (gcc *GoodsCategoryCreate) Mutation() *GoodsCategoryMutation {
	return gcc.mutation
}

// Save creates the GoodsCategory in the database.
func (gcc *GoodsCategoryCreate) Save(ctx context.Context) (*GoodsCategory, error) {
	var (
		err  error
		node *GoodsCategory
	)
	gcc.defaults()
	if len(gcc.hooks) == 0 {
		if err = gcc.check(); err != nil {
			return nil, err
		}
		node, err = gcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodsCategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gcc.check(); err != nil {
				return nil, err
			}
			gcc.mutation = mutation
			if node, err = gcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gcc.hooks) - 1; i >= 0; i-- {
			if gcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gcc *GoodsCategoryCreate) SaveX(ctx context.Context) *GoodsCategory {
	v, err := gcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcc *GoodsCategoryCreate) Exec(ctx context.Context) error {
	_, err := gcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcc *GoodsCategoryCreate) ExecX(ctx context.Context) {
	if err := gcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gcc *GoodsCategoryCreate) defaults() {
	if _, ok := gcc.mutation.CreateTime(); !ok {
		v := goodscategory.DefaultCreateTime()
		gcc.mutation.SetCreateTime(v)
	}
	if _, ok := gcc.mutation.UpdateTime(); !ok {
		v := goodscategory.DefaultUpdateTime()
		gcc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gcc *GoodsCategoryCreate) check() error {
	if _, ok := gcc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "create_time"`)}
	}
	if _, ok := gcc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "update_time"`)}
	}
	if _, ok := gcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	return nil
}

func (gcc *GoodsCategoryCreate) sqlSave(ctx context.Context) (*GoodsCategory, error) {
	_node, _spec := gcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (gcc *GoodsCategoryCreate) createSpec() (*GoodsCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &GoodsCategory{config: gcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: goodscategory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: goodscategory.FieldID,
			},
		}
	)
	if value, ok := gcc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: goodscategory.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := gcc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: goodscategory.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := gcc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: goodscategory.FieldName,
		})
		_node.Name = value
	}
	if nodes := gcc.mutation.GoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   goodscategory.GoodsTable,
			Columns: []string{goodscategory.GoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: goods.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoodsCategoryCreateBulk is the builder for creating many GoodsCategory entities in bulk.
type GoodsCategoryCreateBulk struct {
	config
	builders []*GoodsCategoryCreate
}

// Save creates the GoodsCategory entities in the database.
func (gccb *GoodsCategoryCreateBulk) Save(ctx context.Context) ([]*GoodsCategory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gccb.builders))
	nodes := make([]*GoodsCategory, len(gccb.builders))
	mutators := make([]Mutator, len(gccb.builders))
	for i := range gccb.builders {
		func(i int, root context.Context) {
			builder := gccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoodsCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gccb *GoodsCategoryCreateBulk) SaveX(ctx context.Context) []*GoodsCategory {
	v, err := gccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gccb *GoodsCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := gccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gccb *GoodsCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := gccb.Exec(ctx); err != nil {
		panic(err)
	}
}
