// Code generated by entc, DO NOT EDIT.

package ent

import (
	"go-web/lesson/chapter6_1/repository/ent/goods"
	"go-web/lesson/chapter6_1/repository/ent/goodscategory"
	"go-web/lesson/chapter6_1/repository/ent/order"
	"go-web/lesson/chapter6_1/repository/ent/schema"
	"go-web/lesson/chapter6_1/repository/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	goodsMixin := schema.Goods{}.Mixin()
	goodsMixinFields0 := goodsMixin[0].Fields()
	_ = goodsMixinFields0
	goodsFields := schema.Goods{}.Fields()
	_ = goodsFields
	// goodsDescCreateTime is the schema descriptor for create_time field.
	goodsDescCreateTime := goodsMixinFields0[0].Descriptor()
	// goods.DefaultCreateTime holds the default value on creation for the create_time field.
	goods.DefaultCreateTime = goodsDescCreateTime.Default.(func() time.Time)
	// goodsDescUpdateTime is the schema descriptor for update_time field.
	goodsDescUpdateTime := goodsMixinFields0[1].Descriptor()
	// goods.DefaultUpdateTime holds the default value on creation for the update_time field.
	goods.DefaultUpdateTime = goodsDescUpdateTime.Default.(func() time.Time)
	// goods.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	goods.UpdateDefaultUpdateTime = goodsDescUpdateTime.UpdateDefault.(func() time.Time)
	goodscategoryMixin := schema.GoodsCategory{}.Mixin()
	goodscategoryMixinFields0 := goodscategoryMixin[0].Fields()
	_ = goodscategoryMixinFields0
	goodscategoryFields := schema.GoodsCategory{}.Fields()
	_ = goodscategoryFields
	// goodscategoryDescCreateTime is the schema descriptor for create_time field.
	goodscategoryDescCreateTime := goodscategoryMixinFields0[0].Descriptor()
	// goodscategory.DefaultCreateTime holds the default value on creation for the create_time field.
	goodscategory.DefaultCreateTime = goodscategoryDescCreateTime.Default.(func() time.Time)
	// goodscategoryDescUpdateTime is the schema descriptor for update_time field.
	goodscategoryDescUpdateTime := goodscategoryMixinFields0[1].Descriptor()
	// goodscategory.DefaultUpdateTime holds the default value on creation for the update_time field.
	goodscategory.DefaultUpdateTime = goodscategoryDescUpdateTime.Default.(func() time.Time)
	// goodscategory.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	goodscategory.UpdateDefaultUpdateTime = goodscategoryDescUpdateTime.UpdateDefault.(func() time.Time)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreateTime is the schema descriptor for create_time field.
	orderDescCreateTime := orderMixinFields0[0].Descriptor()
	// order.DefaultCreateTime holds the default value on creation for the create_time field.
	order.DefaultCreateTime = orderDescCreateTime.Default.(func() time.Time)
	// orderDescUpdateTime is the schema descriptor for update_time field.
	orderDescUpdateTime := orderMixinFields0[1].Descriptor()
	// order.DefaultUpdateTime holds the default value on creation for the update_time field.
	order.DefaultUpdateTime = orderDescUpdateTime.Default.(func() time.Time)
	// order.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	order.UpdateDefaultUpdateTime = orderDescUpdateTime.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
